ALTER DATABASE gdcpc DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE coach DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE teams DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER DATABASE gdcpc DEFAULT CHARACTER SET gbk COLLATE gbk_chinese_ci;
ALTER TABLE coach DEFAULT CHARACTER SET gbk COLLATE gbk_chinese_ci;
ALTER TABLE teams DEFAULT CHARACTER SET gbk COLLATE gbk_chinese_ci;
